# app.yaml
runtime: python39
env: standard
instance_class: F4_1G

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.75

network:
  session_affinity: true

entrypoint: streamlit run seo_app.py --server.port $PORT --server.address=0.0.0.0
