# cloudbuild.yaml - Bereinigte Version für IAP-Authentifizierung

steps:
# Step #0: Erstelle secrets.toml mit API-Schlüsseln
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      mkdir -p .streamlit
      # Erstelle die secrets.toml nur mit API-Schlüsseln
      echo 'gemini_api_key = "'$(gcloud secrets versions access latest --secret=gemini-api-key)'"' > .streamlit/secrets.toml

# Step #1: Docker-Container bauen
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/seo-helper-repo/seo-helper-image:$COMMIT_SHA', '.']

# Step #2: Container in die Artifact Registry pushen
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/seo-helper-repo/seo-helper-image:$COMMIT_SHA']

# Step #3: Container auf Cloud Run deployen
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '$_SERVICE_NAME'
    - '--image'
    - 'europe-west1-docker.pkg.dev/$PROJECT_ID/seo-helper-repo/seo-helper-image:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--session-affinity'

options:
  logging: CLOUD_LOGGING_ONLY